title: David Stancu
email: dstancu@nyu.edu
description: > # this means to ignore newlines until "baseurl:"
  Polyglot software architect and car enthusiast living in New York City.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: mach_kernel
github_username:  mach-kernel
linkedin_username: david-stancu-84557335
instagram_username: pragmadev

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
assets:
  compress:
    js: true
  sources:
    - _assets/css
    - _assets/javascripts
exclude:
  - node_modules